services:
  - type: web
    name: irfanbot-pro
    env: node
    plan: starter
    buildCommand: npm ci
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
    disk:
      name: session-disk
      mountPath: /opt/render/project/src/auth
      sizeGB: 1
    healthCheckPath: /health
    headers:
      - path: /*
        name: X-Powered-By
        value: IrfanBot